document.addEventListener('DOMContentLoaded', () => {
    const options = document.querySelectorAll('.option');
    
    options.forEach(option => {
        option.addEventListener('click', () => {
            const optionNumber = option.getAttribute('data-option');
            const optionText = option.querySelector('.option-text').textContent;
            
            // For now, just log the selection - this will be replaced with API calls to the LLM later
            console.log(`Selected option ${optionNumber}: ${optionText}`);
            
            // Visual feedback on selection
            highlightSelection(option);
            
            // In the future, this would trigger the next set of questions from the LLM
            // For now, show a placeholder message
            showPlaceholderResponse(optionNumber, optionText);
        });
    });
    
    function highlightSelection(selectedOption) {
        // Remove any existing 'selected' class
        options.forEach(opt => opt.classList.remove('selected'));
        
        // Add 'selected' class to the clicked option
        selectedOption.classList.add('selected');
    }
    
    function showPlaceholderResponse(optionNumber, optionText) {
        // Create a response element if it doesn't exist
        let responseElement = document.querySelector('.response');
        
        if (!responseElement) {
            responseElement = document.createElement('div');
            responseElement.className = 'response';
            document.querySelector('main').appendChild(responseElement);
        }
        
        // Show a placeholder message
        responseElement.innerHTML = `
            <div class="response-content">
                <h2>You selected: ${optionText}</h2>
                <p>This is a placeholder for the next set of questions that would be generated by the LLM.</p>
                <p>In the full implementation, the system would now present you with more specific questions related to your ${optionText.toLowerCase()} issue.</p>
                <button class="back-button">Back to Categories</button>
            </div>
        `;
        
        // Add event listener to the back button
        const backButton = responseElement.querySelector('.back-button');
        backButton.addEventListener('click', () => {
            responseElement.remove();
            options.forEach(opt => opt.classList.remove('selected'));
        });
    }
});
